{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common-helm-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common-helm-chart.labels" . | nindent 4 }}
    {{- with .Values.configMap.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- with .Values.configMap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}