{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "common-helm-chart.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "common-helm-chart.labels" . | nindent 4 }}
    {{- with .Values.networkPolicy.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.networkPolicy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "common-helm-chart.name" . }}
      release: {{ .Release.Name }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- end }}
{{- end }}