{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "common-helm-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common-helm-chart.labels" . | nindent 4 }}
    {{- with .Values.podDisruptionBudget.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.podDisruptionBudget.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "common-helm-chart.name" . }}
      release: {{ .Release.Name }}
  {{- if .Values.podDisruptionBudget.unhealthyPodEvictionPolicy }}
  unhealthyPodEvictionPolicy: {{ .Values.podDisruptionBudget.unhealthyPodEvictionPolicy }}
  {{- end }}
{{- end }}