{{- if .Values.service.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "common-helm-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common-helm-chart.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  type: {{ .Values.service.type }}

  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}

  {{- if and (eq .Values.service.type "ExternalName") .Values.service.externalName }}
  externalName: {{ .Values.service.externalName }}
  {{- end }}

  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}

  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}

  selector:
    app: {{ include "common-helm-chart.name" . }}
    release: {{ .Release.Name }}

  {{- if .Values.service.ports }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
      {{- if and (eq $.Values.service.type "NodePort") .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
  {{- end }}

  {{- if .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml .Values.service.externalIPs | nindent 4 }}
  {{- end }}

{{- end }}
