name: Helm Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Helm Lint & Validate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Lint Helm Chart
        run: helm lint . --strict

      - name: Template check
        run: helm template test . -f values.yaml > /dev/null


  deploy:
    runs-on: self-hosted   # 👈 YOUR MAC RUNNER
    needs: lint
    name: Deploy to Minikube

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check cluster connection
        run: kubectl get nodes

      - name: Helm Upgrade/Install
        run: |
          helm upgrade --install myapp . \
            -f values.yaml \
            --namespace default \
            --create-namespace

      - name: Verify deployment
        run: |
          kubectl get pods
          kubectl get svc
